from django.urls import path
from . import views

urlpatterns = [
    path('', views.my_drive_view, name='my-box'),
    path('corbeille', views.trash_bin_view, name='my-trash'),
    path('corbeille/<slug:slug>/restore', views.restore_deleted_file_view, name='restore-deleted-file'),
    path('corbeille/<slug:slug>/archive', views.archive_file_view, name='archive-deleted-file'),
    path('nouveau-dossier', views.create_folder_view, name='new-folder'),
    path('dossier/<slug:slug>/supprimer', views.delete_folder_view, name='delete-folder'),
    path('dossier/<slug:slug>/partager', views.share_folder_view, name='share-folder'),
    path('dossier/<slug:slug>/download', views.download_folder_view, name='download-folder'),
    path('dossier/<slug:slug>/rename', views.rename_folder_view, name='rename-folder'),
    path('fichier/<slug:slug>/partager', views.share_file_view, name='share-file'),
    path('fichier/<slug:slug>/rename/submit', views.rename_file_info_view, name='rename-file-info'),
    path('fichier/<slug:slug>/details', views.file_details_view, name='file-details'),
    path('fichier/<slug:slug>/view', views.view_file_content_view, name='view-file'),
    path('fichier/<slug:slug>/supprimer', views.delete_file_view, name='delete-file'),
    path('fichier/<slug:slug>/download', views.download_file_view, name='download-file'),
    path('fichier/importer', views.upload_files_view, name='upload-files'),
    path('favoris/<slug:slug>', views.toggle_favorite_view, name='toggle-favorite'),
    path('contacts', views.all_contacts_view, name='my-contacts'),
    path('contacts/new', views.create_contact_view, name='create-new-contact'),
    path('contacts/groups/new', views.create_contact_group_view, name='create-contact-group'),
    path('contacts/groups/<int:group_id>/details', views.contact_group_details_view, name='contact-group-details'),
    path('contacts/groups/<int:group_id>/edit', views.edit_contact_group_view, name='edit-contact-group'),
    path('contacts/groups/<int:group_id>/delete', views.delete_contact_group_view, name='delete-contact-group'),
    path('contacts/<int:contact_id>/add-to-item', views.add_contact_to_shared_item_view, name='add-contact-to-item'),
    path('contacts/<int:contact_id>/remove-from-item', views.remove_contact_from_shared_item_view, name='remove-contact-from-item'),
]